version: "3"
services: 
 hub: #this name can be anything
  image: selenium/hub:4.16
 chrome:
  image: selenium/node-chrome:4.16
  shm_size: '2g'
  depends_on:
  - hub
  deploy:
    replicas: 0
    #here either we can get rid of values or follow another approach
  #environment:
  #- SE_EVENT_BUS_HOST=hub
  #- SE_EVENT_BUS_PUBLISH_PORT=4442
  #- SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #- SE_NODE_OVERRIDE_MAX_SESSIONs=true
  #- SE_NODE_MAX_SESSIONS=4
  env_file: .env
 firefox:
  image: selenium/node-firefox:4.16
  shm_size: '2g'
  depends_on:
  - hub
  deploy:
    replicas: 0
  env_file: .env